version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - cp package* ./build
      - cd build && npm install --production
  post_build:
    commands:
      - aws cloudformation package --template-file sam.template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - sam.template.yml
    - outputtemplate.yml
cache:
  paths:
    - node_modules/*
    - build/node_modules/*
