AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: house finder api
Parameters:
  ServiceRoleName:
    Description: Name of the service role who will administer the KMS key
      we create. This user will be able to encrypt values and manage the key.
    Type: String
  IamUserName:
    Description: Name of the iam user who will administer the KMS key
      we create. This user will be able to encrypt values and manage the key.
    Type: String
Resources:
  HouseFinderApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: ./build
      Role:
        Fn::GetAtt:
        - HfApiRole
        - Arn
      Timeout: 10
      FunctionName: house-finder-api
      Environment:
        Variables:
          PS_PATH: house-finder-api
      Events:
        hfAPI:
          Type: Api
          Properties:
            Path: /house-finder-api
            Method: ANY
  HfApiEncKey:
    Properties:
      Description: Encryption key for secret config values for the Parameter Store
      EnableKeyRotation: false
      Enabled: true
      KeyPolicy:
        Id: key-default-1
        Statement:
        - Action:
          - kms:Create*
          - kms:Describe*
          - kms:Enable*
          - kms:List*
          - kms:Put*
          - kms:Update*
          - kms:Revoke*
          - kms:Disable*
          - kms:Get*
          - kms:Delete*
          - kms:ScheduleKeyDeletion
          - kms:CancelKeyDeletion
          Effect: Allow
          Principal:
            AWS:
            - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/${ServiceRoleName}
            - Fn::Sub: arn:aws:iam::${AWS::AccountId}:user/${IamUserName}
          Resource: '*'
          Sid: Allow administration of the key
        - Action:
          - kms:Encrypt
          - kms:Decrypt
          - kms:ReEncrypt*
          - kms:GenerateDataKey*
          - kms:DescribeKey
          Effect: Allow
          Principal:
            AWS:
              Fn::GetAtt:
              - HfApiRole
              - Arn
            - Fn::Sub: arn:aws:iam::${AWS::AccountId}:user/${IamUserName}
          Resource: '*'
          Sid: Allow use of the key
        Version: '2012-10-17'
    Type: AWS::KMS::Key
  HfApiEncKeyAlias:
    Properties:
      AliasName: alias/HfApiEncKey
      TargetKeyId:
        Ref: HfApiEncKey
    Type: AWS::KMS::Alias
  HfApiRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - ssm:GetParameter*
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/house-finder-api
          Version: '2012-10-17'
        PolicyName: HfApiParameterAccess
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: HfApiLambdaBasicExecution
      - PolicyDocument:
          Statement:
          - Action:
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: HfApiXRayAccess
    Type: AWS::IAM::Role
  