AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: house finder api
Resources:
  HouseFinderApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: ./build
      Events:
        hfAPI:
          Type: Api
          Properties:
            Path: /house-finder-api
            Method: ANY